name: rl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - swig
  - pip
  - pip:
    - stable-baselines3
    - sb3-contrib
    - gymnasium[all]
    - tensorboard
    - jupyter
    - matplotlib
    - scipy
    - numpy
    - pandas
    - pytest
    - pre-commit
    - ruff
    - nbqa
